---
abstract: 'Support of the pack scheme in URI.'
author:
  - 'Douglas Christopher Wilson <doug@somethingdoug.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
  Test::Most: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: URI-pack
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Carp: 0
  Readonly: 1.03
  URI: 0
  base: 0
  namespace::clean: 0
  perl: 5.8.1
resources:
  homepage: http://github.com/dougwilson/perl5-uri-pack/
  license: http://dev.perl.org/licenses/
  repository: git://github.com/dougwilson/perl5-uri-pack.git
version: 0.001
